<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE info 
[
	<!ELEMENT details (bookid,bookname,author,edition,publisher)>
	<!ELEMENT info (#PCDATA)>
	<!ELEMENT bookid (#PCDATA)>
	<!ELEMENT bookname (#PCDATA)>
	<!ELEMENT author (#PCDATA)>
	<!ELEMENT edition (#PCDATA)>
	<!ELEMENT publisher (#PCDATA)>
]>
<details> 
	<info>
		<bookid>10122</bookid>
		<bookname>C</bookname>
		<author>KM</author>
		<edition>3rd edition</edition>
		<publisher>MC Graw Hill</publisher>
	</info>
		<info>
		<bookid>10132</bookid>
		<bookname>C++</bookname>
		<author>JT</author>
		<edition>menonk484@gmail.com</edition>
		<publisher>MC Graw Hill</publisher>
	</info>
		<info>
		<bookid>10142</bookid>
		<bookname>Python</bookname>
		<author>KT</author>
		<edition>menonk484@gmail.com</edition>
		<publisher>MC Graw Hill</publisher>
	</info>
</details>